powerlevel9k_whoami(){
  echo `whoami`
}

POWERLEVEL9K_CUSTOM_WHOAMI="powerlevel9k_whoami"
POWERLEVEL9K_CUSTOM_WHOAMI_BACKGROUND='024'
POWERLEVEL9K_CUSTOM_WHOAMI_FOREGROUND='white'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_whoami dir vcs)

POWERLEVEL9K_BATTERY_ICON=''
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='024'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='024'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='024'
POWERLEVEL9K_BATTERY_CHARGING='yellow'
POWERLEVEL9K_BATTERY_CHARGED='green'
POWERLEVEL9K_BATTERY_DISCONNECTED='cyan'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(rbenv history vi_mode)
